import { CC, HYN, KEYS, LV, META, MST, O, RC, RK, S, U, UI, V, lvl } from '../core/data.js'
import { agH, chart, hypH, igH, sensRows } from '../ui/panels.js'
import { ALT, BP, D, TG, VX, VZ, tele } from '../core/world.js'
import { RT, STN } from '../scene/volcanoScene.js'

/* ---------- pages ---------- */
export const NAV=[['dash','Dashboard','▦'],['map','Live Map','◉'],['sensors','Sensors','⌁'],['ai','AI Analysis','✦'],['drone','Drone Missions','✈'],['alerts','Alerts','▲'],['reports','Reports','▤'],['settings','Settings','⚙']];
export const SC=`<svg class="bgs" viewBox="0 0 1200 700" preserveAspectRatio="xMidYMax slice"><defs><linearGradient id="sk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0a1230"/><stop offset=".6" stop-color="#5a3552"/><stop offset="1" stop-color="#d9603f"/></linearGradient><radialGradient id="gw"><stop offset="0" stop-color="#ff8a3d" stop-opacity=".85"/><stop offset="1" stop-color="#ff8a3d" stop-opacity="0"/></radialGradient></defs><rect width="1200" height="700" fill="url(#sk)"/><ellipse cx="800" cy="290" rx="300" ry="170" fill="url(#gw)"/><path d="M0 560L160 470 300 520 470 430 640 540 1200 480V700H0Z" fill="#141a33" opacity=".8"/><path d="M430 700L700 270 740 255 790 275 1080 700Z" fill="#1b1f35"/><path d="M735 262L720 350 690 460M765 268L790 380 850 520M750 265L752 420" stroke="#ff6a2f" stroke-width="3" fill="none" opacity=".8"/><ellipse cx="760" cy="190" rx="120" ry="60" fill="#6b6b78" opacity=".35"/><ellipse cx="800" cy="130" rx="170" ry="55" fill="#8a8a98" opacity=".25"/><path d="M0 700V610L220 580 480 630 800 600 1200 640V700Z" fill="#070b16"/></svg><div class="bgs" style="background:linear-gradient(90deg,rgba(6,11,22,.75),transparent 70%)"></div>`;
export const LAND=`<div class="land">${SC}<div class="nav"><span class="brand">▲ VOLCANO <b>ZERO</b></span><span class="sp"></span><a href="#/">Home</a><a href="#loop" onclick="document.getElementById('loop').scrollIntoView();return false">How it works</a><a class="btn" href="#/login">Login</a><a class="btn pri" href="#/signup">Sign Up</a></div>
<div class="hero"><span class="tags gl">AI-powered · Real-time · Multi-sensor</span><h1>VOLCANO <b>ZERO</b></h1><h2>Investigate. Understand. Respond.</h2><p>An agentic AI platform that monitors volcanic activity, resolves uncertain signals, sends drones to collect the data that matters most, and supports timely, safe decisions.</p><div class="row" style="max-width:340px"><a class="btn pri" href="#/signup" style="text-align:center">Get started</a><a class="btn" href="#/app/dash" data-demo="1" style="text-align:center">Watch demo</a></div></div>
<div class="loop" id="loop">${['Observe','Detect','Investigate','Choose next best information','Deploy resource','Collect data','Update hypothesis','Reassess risk and act'].map((s,i)=>`<div class="gl"><b>${i+1}</b>${s}</div>`).join('')}</div></div>`;
export const authH=m=>`<div class="auth">${SC}<div><span class="brand">▲ VOLCANO <b>ZERO</b></span><h1 style="margin:14px 0 8px">VOLCANO <b>ZERO</b></h1><p>AI-powered investigation &amp; response</p><h2 style="font-weight:500;margin-top:60px">Smarter decisions.<br>Safer communities.</h2></div><div class="gl p" style="padding:26px"><h2>${m==='login'?'Welcome back':'Create account'}</h2><p class="mu" style="margin-bottom:14px">${m==='login'?'Log in to continue your mission':'Join VOLCANO ZERO'}</p>
${m==='signup'?'<div class="f"><label for="nm">Full name</label><input id="nm" autocomplete="name"></div>':''}<div class="f"><label for="em">Email</label><input id="em" type="email" placeholder="you@example.com" autocomplete="email"></div><div class="f"><label for="pw">Password</label><div class="row"><input id="pw" type="password" autocomplete="${m==='login'?'current':'new'}-password" style="flex:1"><button class="btn" style="flex:none" data-a="pw" type="button">Show</button></div></div>
${m==='signup'?'<div class="f"><label for="pw2">Confirm password</label><input id="pw2" type="password"></div>':'<p style="text-align:right;margin:-4px 0 8px"><a href="#" data-a="forgot" class="mu">Forgot password?</a></p>'}<div class="msg" id="msg" role="status"></div>
<button class="btn pri" style="width:100%" data-a="${m}">${m==='login'?'Sign in':'Create account'}</button><p class="mu" style="text-align:center;margin:12px 0 8px;font-size:12px">or continue with</p><div class="row"><button class="btn" disabled title="Needs an auth provider">Google</button><button class="btn" disabled title="Needs an auth provider">GitHub</button></div>
<p style="text-align:center;margin-top:14px">${m==='login'?'No account? <a href="#/signup" style="color:var(--cy)">Sign up</a>':'Have an account? <a href="#/login" style="color:var(--cy)">Sign in</a>'}</p><p class="mu" style="font-size:11px;margin-top:8px;text-align:center">Prototype: credentials are not verified.</p></div></div>`;
export const DASH=`<div class="dash"><div class="ms" id="mapslot"></div><aside><section class="gl p" id="sensP"></section><section class="gl p" id="hyp"></section></aside></div><div class="bot"><section class="gl p"><h3>AI Investigation Timeline</h3><div id="tl"></div></section><section class="gl p"><h3>Recommended Actions</h3><div id="act"></div></section></div>`;
export const tiles=(a)=>`<div class="tiles">${a.map(x=>`<div><small>${x[0]}</small><b style="color:${x[2]||'inherit'}">${x[1]}</b></div>`).join('')}</div>`;
export const VIEWS={
sensors:()=>{const k=UI.sel,m=META[k],l=lvl(k);return `<div class="g2"><section class="gl p"><h3>Sensors</h3>${sensRows()}</section><section class="gl p"><h3>${m[1]}</h3><b style="font-size:34px;color:${CC[l]}">${m[3](S.cur[k])}</b> <span style="color:${CC[l]}">${LV[l]}</span>${chart(S.h[k],CC[l])}${tiles([['Location',m[2]],['Last updated',V.CLK],['Status',LV[l],CC[l]],['Data source','Simulated feed']])}<p style="margin-top:12px"><a class="btn" href="#/app/sensor/${k}">Open sensor details</a></p></section></div>`},
ai:()=>`<div class="g3"><div style="display:grid;gap:14px"><section class="gl p"><h3>Current Situation</h3><p>${S.sit}</p></section><section class="gl p"><h3>Evidence</h3>${KEYS.map(k=>`<div class="sr" style="cursor:default"><span>${META[k][0]}</span><b style="color:${CC[lvl(k)]}">${META[k][3](S.cur[k])} · ${LV[lvl(k)]}</b></div>`).join('')}</section></div><div style="display:grid;gap:14px"><section class="gl p"><h3>Active Hypotheses</h3>${hypH()}</section><section class="gl p"><h3>Information Gain</h3>${igH()}</section></div><div style="display:grid;gap:14px"><section class="gl p"><h3>AI Reasoning</h3><p>${S.why}</p></section><section class="gl p"><h3>Next Best Action</h3><p><b>${S.next}</b></p></section><section class="gl p"><h3>Agent Activity</h3><div class="agp" style="position:static;width:auto;background:none;border:0;box-shadow:none;padding:0">${agH()}</div></section></div></div>`,
drone:()=>{const d=tele(),pr=!S.mn?0:S.ms===0?5:S.ms===1?5+55*D.fp:S.ms===2?65:S.ms===3?70+30*D.fp:100;return `<div class="g2" style="grid-template-columns:1fr 320px"><section class="gl p"><a class="btn" href="#/app/mission" style="float:right">Mission details</a><h3>${S.mn||'No active mission'} <small>${S.mn?S.dst:''}</small></h3><svg viewBox="0 0 100 100" style="width:100%;max-height:420px;background:#0a1730;border-radius:12px"><circle cx="56" cy="46" r="40" fill="#14301f"/><circle cx="56" cy="46" r="40" fill="none" stroke="#38bdf8" stroke-opacity=".3"/><circle cx="${50+VX}" cy="${50+VZ}" r="14" fill="#f43f5e" fill-opacity=".2"/><polyline points="${50+BP[0]},${50+BP[1]} ${50+TG[0]},${50+TG[1]}" stroke="${RT.alt?'#f43f5e':'#38e8ff'}" stroke-dasharray="2 1.5" fill="none" stroke-width=".8" style="display:${S.mn?'':'none'}"/><polyline points="${ALT.map(p=>(50+p[0])+','+(50+p[1])).join(' ')}" stroke="#34d399" stroke-dasharray="2 1.5" fill="none" stroke-width=".8" style="display:${RT.alt?'':'none'}"/><circle cx="${50+BP[0]}" cy="${50+BP[1]}" r="2" fill="#38bdf8"/><circle cx="${50+TG[0]}" cy="${50+TG[1]}" r="2.4" fill="none" stroke="#fbbf24"/><circle id="dd" cx="${50+D.x}" cy="${50+D.z}" r="2" fill="#fff"/></svg>
<div class="bar" style="margin:12px 0"><i style="width:${pr}%;background:var(--cy)"></i></div>${tiles([['Progress',Math.round(pr)+'%'],['Altitude',d.alt+' m'],['Speed',d.spd+' m/s'],['Battery',d.bat+'%']])}${tiles([['Signal',d.sig],['To target',d.dist+' m'],['Weather',S.wx],['Drone','DRONE-01']])}</section><section class="gl p"><h3>Mission Steps</h3>${S.mn?MST.map((s,i)=>`<div class="st ${i<S.ms?'d':i===S.ms?'a':''}"><i></i>${s}</div>`).join(''):'<p class="mu">No mission yet. The Mission Planner creates one when the AI picks a measurement. Start the scenario on the dashboard.</p>'}</section></div>`},
alerts:()=>{const f={All:-1,High:2,Medium:1,Info:0},l=S.al.filter(a=>f[UI.f]<0||a.s===f[UI.f]);return `<section class="gl p"><h3>Alerts &amp; Notifications — risk ${RK[S.risk]}</h3><div class="tab">${Object.keys(f).map(x=>`<button class="btn${x===UI.f?' on':''}" data-f="${x}">${x}</button>`).join('')}</div>${l.length?l.map(a=>`<div class="al"><span class="mu">${a.t}</span><span>${a.m}</span><span class="pill" style="background:${['#12507a','#6b4f0f','#7a1630'][a.s]}">${['Info','Medium','High'][a.s]}</span></div>`).join(''):'<p class="mu">No alerts yet.</p>'}</section>`},
reports:()=>`<div class="g3">${[['sit','Situation Report','Current volcanic activity and AI analysis'],['mis','Mission Report','Drone mission details and collected data'],['sen','Sensor Report','Sensor data and trends']].map(r=>`<section class="gl p"><h3>${r[1]}</h3><p class="mu" style="margin-bottom:12px">${r[2]}</p><button class="btn pri" data-rep="${r[0]}">Generate</button></section>`).join('')}</div><section class="gl p" style="margin-top:14px"><pre>${UI.rep||'Choose a report to generate it from the current simulation state.'}</pre></section>`,
settings:()=>`<div class="g2" style="grid-template-columns:320px 1fr"><section class="gl p"><h3>Profile</h3><div class="av" style="width:56px;height:56px;display:grid;place-items:center;font-size:22px">${U.name[0]}</div><p style="margin-top:10px"><b>${U.name}</b></p><p class="mu">${U.email}</p><br><a class="btn" href="#/">Log out</a></section><section class="gl p"><h3>Settings</h3>${[['rm','Reduce motion',O.rm],['smoke','Volcanic smoke effects',O.smoke],['lab','3D labels',O.lab]].map(t=>`<div class="tg"><span>${t[1]}</span><button class="btn" data-tg="${t[0]}" role="switch" aria-checked="${!!t[2]}">${t[2]?'On':'Off'}</button></div>`).join('')}<div class="tg"><span>Scenario speed</span><button class="btn" data-tg="sp">${O.sp}×</button></div></section></div>`};
VIEWS.profile=()=>`<div class="g2" style="grid-template-columns:340px 1fr"><section class="gl p"><div class="av" style="width:72px;height:72px;display:grid;place-items:center;font-size:28px">${U.name[0]}</div><h3 style="margin-top:12px;font-size:18px">${U.name}</h3><p class="mu">${U.email}</p><p class="mu">Role: Duty scientist</p><br><a class="ni" href="#/app/profile">👤 My Profile</a><a class="ni" href="#/app/settings">⚙ Settings</a><a class="ni" href="#/app/alerts">🔔 Notifications</a><a class="ni" href="#/" style="color:#ff8a9a">⎋ Logout</a></section><section class="gl p"><h3>Session summary</h3>${tiles([['Risk level',RK[S.risk],RC[S.risk]],['Alerts today',S.al.length],['High alerts',S.al.filter(a=>a.s===2).length,'#f43f5e'],['Mission',S.mn?S.dst:'None']])}<p class="mu" style="margin-top:14px">Alerts and missions come from the current simulation run.</p></section></div>`;
export const back=h=>`<a class="btn" href="${h}" style="float:right">← Back</a>`;
VIEWS.sensor=()=>{const k=UI.sel,m=META[k],l=lvl(k),a=S.h[k];return `<section class="gl p">${back('#/app/sensors')}<h3>Sensor Details</h3><div class="tab">${KEYS.map(x=>`<a class="btn${x===k?' on':''}" href="#/app/sensor/${x}">${META[x][0]}</a>`).join('')}</div><p class="mu">${m[1]}</p><b style="font-size:40px;color:${CC[l]}">${m[3](S.cur[k])}</b> <span style="color:${CC[l]}">${LV[l]}</span>${chart(a,CC[l])}${tiles([['Location',m[2]],['Last updated',V.CLK],['Status',LV[l],CC[l]],['Data source','Simulated feed']])}${tiles([['Minimum',m[3](Math.min(...a))],['Maximum',m[3](Math.max(...a))],['Warning at',m[3](m[4][0])],['Critical at',m[3](m[4][1])]])}<p style="margin-top:12px"><a class="btn" href="#/app/map" data-st="${STN.find(x=>x.k===k).id}">Show on 3D map</a></p></section>`};
VIEWS.mission=()=>{const d=tele();return `<section class="gl p">${back('#/app/drone')}<h3>Mission Details — ${S.mn||'none'}</h3>${S.mn?`<p>Status: <b>${S.dst}</b></p>${tiles([['Drone','DRONE-01'],['Battery',d.bat+'%'],['Altitude',d.alt+' m'],['Signal',d.sig]])}<h3 style="margin-top:16px">Steps</h3>${MST.map((t,i)=>`<div class="st ${i<S.ms?'d':i===S.ms?'a':''}"><i></i>${t}</div>`).join('')}<h3 style="margin-top:16px">Mission log</h3>${S.tl.filter(e=>/drone|route|wind|gas|mission/i.test(e.m)).map(e=>`<div class="te"><i style="background:#38bdf8"></i><span class="mu">${e.t}</span><span>${e.m}</span></div>`).join('')}`:'<p class="mu">No mission yet. Start the scenario on the dashboard; the Mission Planner creates one.</p>'}</section>`};
export const REP={sit:()=>['SITUATION REPORT','Risk: '+RK[S.risk]+' · Weather: '+S.wx,...KEYS.map(k=>META[k][0]+': '+META[k][3](S.cur[k])+' ('+LV[lvl(k)]+')'),'Assessment: '+S.sit,'Top hypothesis: '+HYN[S.hy.indexOf(Math.max(...S.hy))]+' '+Math.max(...S.hy)+'%','Next action: '+S.next].join('\n'),mis:()=>S.mn?['MISSION REPORT','Mission: '+S.mn,'Status: '+S.dst,'Battery: '+tele().bat+'%','Steps completed: '+Math.min(S.ms,4)+'/4','Events:',...S.tl.filter(e=>/drone|route|wind|gas/i.test(e.m)).map(e=>e.t+'  '+e.m)].join('\n'):'MISSION REPORT\nNo mission has been created yet.',sen:()=>['SENSOR REPORT',...KEYS.map(k=>META[k][2]+' — '+META[k][0]+': now '+META[k][3](S.cur[k])+', min '+META[k][3](Math.min(...S.h[k]))+', max '+META[k][3](Math.max(...S.h[k])))].join('\n')};
