import { ACT5, HY, S, V, hooks, resetS } from './data.js'
import { ALT, BP, D, G0, P40, TG, VX, VZ, cam, follow, sleep } from './world.js'
import { clrRoutes, route } from '../scene/volcanoScene.js'

/* ---------- scenario ---------- */
export function ev(o){if(o.t){S.tl.push({t:o.t,m:o.m,s:o.sev||0});S.al.unshift({t:o.t,m:o.m,s:o.sev||0})}
for(const k of['sit','why','next','ban','st','hy','act','inv','risk','wx','ig','tz'])if(k in o)S[k]=o[k];S.ag=o.ag||{};hooks.refresh()}
export async function run(){if(S.run)return;resetS();S.run=1;V.SEL=null;Object.assign(D,{x:BP[0],z:BP[1],agl:.4,tAgl:.4,bat:100,f:null,fp:0,col:0});clrRoutes();cam(G0);
ev({t:'08:15',m:'All sensors normal. Monitoring started.',ag:{Orchestrator:'Monitoring all feeds'},ban:'PHASE 1 · NORMAL',st:'SCENARIO RUNNING · NORMAL'});await sleep(3500);
S.tg.seis=8.2;cam({tx:2,tz:-14,d:78});ev({t:'08:17',m:'Seismic anomaly detected at North Station.',sev:2,risk:1,hy:HY[1],inv:['seis'],ag:{'Seismic Agent':'Anomaly 8.2 at North Station',Orchestrator:'Opening investigation'},ban:'SEISMIC ANOMALY DETECTED',st:'SEISMIC ANOMALY',sit:'Seismic activity is high (8.2) while gas and deformation are still normal.',why:'A seismic spike alone is ambiguous: it fits magma movement, hydrothermal activity or a faulty sensor.',next:'Cross-check thermal, gas and deformation readings.',act:['Continue monitoring all sensors','Cross-check other sensors','Prepare alert for local authorities']});await sleep(4200);
S.tg.therm=40;ev({t:'08:18',m:'Evidence conflict: gas normal, thermal slightly high, deformation normal.',sev:1,hy:HY[2],inv:['seis','therm'],ag:{'Evidence Agent':'Sensors disagree','Hypothesis Agent':'Reweighting hypotheses'},ban:'CONFLICTING EVIDENCE · INVESTIGATION MODE',st:'INVESTIGATION IN PROGRESS',sit:'Evidence is conflicting. Seismic is high, thermal slightly high, gas and deformation normal.',why:'Signals disagree, so no single hypothesis is dominant. More information is required.',next:'Request a thermal scan.'});await sleep(3800);
ev({t:'08:20',m:'Thermal investigation requested.',inv:['therm'],ag:{Orchestrator:'Requesting thermal scan','Thermal Agent':'Analyzing thermal readings'},ban:'THERMAL INVESTIGATION REQUESTED'});S.tg.therm=48;await sleep(2800);
ev({t:'08:22',m:'Thermal anomaly detected at Summit (48 °C).',sev:1,hy:HY[3],ag:{'Thermal Agent':'Anomaly 48 °C'},ban:'THERMAL ANOMALY DETECTED',sit:'Seismic and thermal readings are high, but gas and deformation are unmeasured at the flank.',why:'Thermal supports magma or hydrothermal activity. The two stay hard to separate.',next:'Choose the measurement that best separates them.'});await sleep(3500);
cam({tx:10,tz:2,d:60});ev({t:'08:23',m:'Gas measurement selected as highest information gain (0.81).',ig:[['Gas',.81],['Thermal',.42],['Deformation',.35],['Seismic',.22]],tz:1,inv:['gas'],ag:{'Information-Gain Agent':'Gas measurement selected'},ban:'INFORMATION GAIN → GAS MEASUREMENT',why:'Gas measurement is expected to reduce uncertainty most: high SO₂ favors magma, low favors hydrothermal.',next:'Deploy drone to collect gas data in Zone A.',act:['Deploy drone to Gas Zone A','Continue monitoring all sensors','Prepare alert for local authorities','Monitor weather conditions']});await sleep(4500);
S.mn='Gas Monitoring — Zone A';S.ms=0;S.dst='Launching';route([BP,TG],0x38e8ff,'main');D.tAgl=10;ev({t:'08:24',m:'Mission Planner created "Gas Monitoring — Zone A". DRONE-01 launching.',ag:{'Mission Planner':'Executing drone mission'},ban:'DRONE-01 DEPLOYED → ZONE A'});await sleep(1500);
S.ms=1;S.dst='In flight';hooks.refresh();await follow([BP,P40],3800,0,.4);
S.tg.wx=38;S.wx='High Wind';route([BP,TG],0xff4d5e,'main');ev({t:'08:25',m:'High wind detected. Current drone route is unsafe.',sev:1,wx:'High Wind',ag:{'Weather Agent':'High wind on route','Mission Planner':'Replanning route'},ban:'HIGH WIND · ROUTE UNSAFE',why:'Wind exceeds the safe limit on the direct route. The Mission Planner must replan.'});await sleep(2400);
route(ALT,0x34d399,'alt');S.tg.wx=14;ev({t:'08:26',m:'Route updated via southern approach. Drone resumed.',wx:'Windy',ag:{'Mission Planner':'Route updated'},ban:'ROUTE UPDATED · DRONE RESUMES',why:'Original route rejected (wind). New route adds distance but stays within safe limits.'});await follow(ALT,5200,.4,.6);
S.ms=2;S.dst='Collecting data';D.col=1;D.tAgl=8;ev({t:'08:27',m:'Drone reached Zone A. Collecting gas data.',ag:{'Gas Agent':'Processing gas measurements'},ban:'COLLECTING GAS DATA · ZONE A'});await sleep(3800);
S.tg.gas=62;D.col=0;S.ms=3;S.dst='Returning to base';follow([TG,BP],5500,0,1).then(()=>{S.ms=4;S.dst='Mission complete';D.tAgl=.4;hooks.refresh()});
ev({t:'08:27',m:'Gas anomaly detected in Zone A (SO₂ 62 ppm).',sev:2,hy:HY[4],inv:[],tz:0,ag:{'Gas Agent':'Anomaly 62 ppm'},ban:'GAS ANOMALY DETECTED',sit:'Gas is now high in Zone A. Seismic, thermal and gas all point the same way.',why:'High SO₂ favors magma movement over hydrothermal activity and sensor faults.',next:'Check deformation and update the hypothesis.'});await sleep(3500);
S.tg.def=1.2;S.tg.therm=52;cam({tx:VX,tz:VZ,d:92,ph:.9});ev({t:'08:28',m:'EVIDENCE CONVERGENCE DETECTED: seismic, gas, thermal HIGH; deformation MODERATE.',sev:2,risk:2,hy:HY[5],ag:{'Evidence Agent':'Evidence converging','Hypothesis Agent':'Magma movement 82%'},ban:'EVIDENCE CONVERGENCE DETECTED',st:'EVIDENCE CONVERGENCE',sit:'Four independent sensors now agree. Magma movement is the leading hypothesis (82%).',why:'Independent sources converge, so sensor malfunction is very unlikely.',next:'Reassess risk zones and alert level.'});await sleep(4500);
ev({t:'08:28',m:'Risk zones updated. Alert level CRITICAL.',sev:2,risk:3,ag:{Orchestrator:'Reassessing risk'},ban:'RISK ESCALATION · CRITICAL',st:'CRITICAL · ESCALATE',wx:'Ash Cloud'});await sleep(3500);
S.run=0;S.done=1;ev({t:'08:29',m:'Escalate to human authorities recommended.',sev:2,ag:{Orchestrator:'Escalating to humans'},ban:'ESCALATE TO HUMAN AUTHORITIES',next:'Escalate to human authorities now.',why:'The risk is critical and decisions about evacuation belong to people.',act:ACT5})}
